remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: LMFDB, Computation, and Number Theory (LuCaNT)
description: This is the main website for the LuCaNT series of conferences.
